# GENERATED FILE — do not edit

KEVIN_BACON = "Kevin Bacon"
FOOTLOOSE = "Footloose"
HERBERT_ROSS = "Herbert Ross"
FRIDAY_THE_13TH = "Friday the 13th (1980 film)"
CITY_ON_A_HILL = "City on a Hill (TV series)"
AMANDA_CLAYTON = "Amanda Clayton"
THE_BET = "The Bet (2016 film)"
CLINT_EASTWOOD = "Clint Eastwood"
CURTIS_HANSON = "Curtis Hanson"
GT5 = "GT5"
GINETTA_GT5_CHALLENGE = "Ginetta GT5 Challenge"
GRAN_TURISMO_5 = "Gran Turismo 5"
GRAN_TURISMO_5_PROLOGUE = "Gran Turismo 5 Prologue"
