[package]
name = "crawler-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
reqwest = { version = "0.12.4", features = ["blocking"] }
scraper = "0.19.0"
titles = { path = "../../titles/" }

[lints.clippy]
pedantic = "warn"
