[workspace]
authors = ["Richard Beaver <rickybeaver3@gmail.com>"]
channels = ["conda-forge"]
name = "wikipedia-path-finder"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

test-crawler-py = "pytest crawlers/crawler_py"
test-crawler-rs = "cargo test --manifest-path ./crawlers/crawler_rs/Cargo.toml"
test-crawler-rs-async = "cargo test --manifest-path ./crawlers/crawler_rs_async/Cargo.toml"
test-all = [{ task = "test-crawler-py" }, { task = "test-crawler-rs" }]

server-py = "python3 -m servers.server_py.main"
server-rs = "cargo run --manifest-path ./servers/server_rs/Cargo.toml"

frontend = "npm --prefix frontend start"

[dependencies]
pylint = ">=3.3.7,<4"
pytest = ">=8.4.1,<9"
flask = ">=3.1.1,<4"
requests = ">=2.32.4,<3"
python-dotenv = ">=1.1.1,<2"
flask-cors = ">=6.0.1,<7"
