[package]
name = "crawler-rs-async"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-channel = "2.5.0"
reqwest = "0.12.4"
scraper = "0.19.0"
tokio = { version = "1.38.0", features = ["full"] }

[lints.clippy]
pedantic = "warn"
